#!/usr/bin/env python2
# You may have to chmod +x this file.

import re
import sys


def main():
    try:
        file_name = sys.argv[1]
    except IndexError:
        return 2

    test_regex = re.compile(
        r"^test-([0-9])-([vimt])\.txt$")
    if not test_regex.match(file_name):
        return 2
    else:
        m = test_regex.match(file_name)
        test_num = int(m.group(1))
        if test_num > 9 or test_num < 0:
            return 2
        flags = []
        for flag in m.group(2):
            flags.append("-%s" % flag)
        flags = " ".join(flags)
        print "%s" % (flags)
        return 0

if __name__ == "__main__":
    sys.exit(main())
